environment:
  git_user_email: normand.erwan@protonmail.com
  git_user_name: NormandErwan
  auth_token:
    secure: rAvGzxn8QfY9CapiOocIVsgDya7dnnh3bRzxAGDntS8axguyhTt1nyH7przrm3LF
install: choco install docfx -y
build_script:
  # Inspired by: https://github.com/docascode/docfx-seed/blob/master/appveyor.yml
  - ps: |
        copy README.md Documentation\index.md
        docfx Documentation\docfx.json
        if ($lastexitcode -ne 0) {
          throw [System.Exception] "docfx build failed with exit code $lastexitcode."
        }

        git clone https://github.com/NormandErwan/ArucoUnity -b gh-pages gh-pages -q
        Remove-Item gh-pages\* -recurse
        Copy-Item _site\* gh-pages -recurse

        git config --global credential.helper store
        Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n"
        git config --global user.email $env:git_user_email
        git config --global user.name $env:git_user_name

        cd gh-pages
        git add -A | out-null
        git commit -m "Documentation update" -q
        git push origin gh-pages -q